version: "3"

services:
  install_laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: install_laravel
    volumes:
      - ../src:/var/www/html
    command: cp /temp_install/. /var/www/html
